# Default application configuration that all configurations inherit from.
# Documentation: https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md
exclude: 'static/src/stylesheets/components/*'

linters:
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: true
    exclude: static/src/stylesheets/module/_search.scss

  ColorKeyword:
    enabled: true

  Comment:
    enabled: false

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true
    exclude:

  MergeableSelector:
    enabled: false

  DuplicateRoot:
    enabled: false

  EmptyLineBetweenBlocks:
    enabled: false
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: false

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: long

  HexNotation:
    enabled: true
    style: lowercase

  HexValidation:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  Indentation:
    enabled: true
    width: 4

  LeadingZero:
    enabled: true
    style:  include_zero

  NameFormat:
    enabled: true
    convention: hyphenated_lowercase

  PlaceholderInExtend:
    enabled: true

  PropertySortOrder:
    enabled: false
    order: margin,

  PropertySpelling:
    enabled: true
    extra_properties: []

  SelectorDepth:
    enabled: true
    max_depth: 4
    exclude: # Exclude if forced to break the inception rule to style third party components

  Shorthand:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true
    exclude:
      - static/src/stylesheets/webfonts*.scss

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes

  TrailingSemicolonAfterPropertyValue:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: false

  UrlFormat:
    enabled: false

  UrlQuotes:
    enabled: false

  ZeroUnit:
    enabled: false

  Compass::*:
    enabled: false